# Generated by Django 5.0.1 on 2024-06-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('emailHandler', '0001_initial'), ('emailHandler', '0002_alter_companydetails_application_status_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('applied_date', models.DateField(auto_now=True)),
                ('application_status', models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('Hr round', 'Hr round'), ('TechnicalRound', 'TechnicalRound'), ('offerletter', 'offerletter')], default='applied', max_length=100)),
            ],
        ),
    ]
