# Generated by Django 5.0.1 on 2024-06-09 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('emailHandler', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='companyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('applied_date', models.DateField(auto_now=True)),
                ('application_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emailHandler.jobstatus')),
            ],
        ),
    ]
