# Generated by Django 5.0.1 on 2024-06-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='application_status',
            field=models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('Hr round', 'Hr round'), ('TechnicalRound', 'TechnicalRound'), ('offerletter', 'offerletter')], default='applied', max_length=100),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='JobStatus',
        ),
    ]
